name: flutter_lint_rules
description: A set of custom lint rules for Flutter apps and packages.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_lints: ^2.0.1