name: flutter_lint_rules
description: A set of custom lint rules for Flutter apps and packages.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.1.0

dev_dependencies:
  # Testing
  test: ^1.22.0
