name: packages
description: An example project that uses the lint rules recommended for Flutter packages.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/flutter_lint_rules.git
      ref: v0.1.0